version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: chainmail:latest
    container_name: chainmail
    restart: unless-stopped
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true
